
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Emre
 */


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javafx.stage.FileChooser;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import tanktool3.javaconnect;
public class MainWindow extends javax.swing.JFrame {
    static Connection conn = null;
    static ResultSet rs = null;
    static PreparedStatement pst = null;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        conn=javaconnect.ConnecrDb();
        Update_table("");
        FillCombobox("");
        get_carID("");
        get_userID("");
        get_fuelID();
    }
    
    public void close(){
        WindowEvent winClosingEvent =  new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    private void Update_table(String username){
        try{
        username=Login_JFrame.get_username();
        String sql= "SELECT CAR.CarName, stationname as Fuelstation,daytime as Daytime,ppLiter as Literprice,literamount as Amount,endcost as Total,y.fuelname as Fuel, x.kmstatus as kmRange\n" +
        "from FuelEntry x join FUEL AS y\n" +
        "ON x.fuelID=y.id\n" +
        "join CAR\n" +
        "on x.carID=CAR.id\n" +
        "join UserData on x.userid=UserData.id where UserData.username='"+Login_JFrame.get_username()+"' ORDER BY x.id DESC";
    
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jFileChooser1 = new javax.swing.JFileChooser();
        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        daytime = new javax.swing.JTextField();
        ppLiter = new javax.swing.JTextField();
        endcost = new javax.swing.JTextField();
        stationname = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        save = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        car_combobox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        literamount = new javax.swing.JTextField();
        my_cars = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        kmstatus = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel1.setText("Car:");

        jLabel2.setText("Date (YYYY.MM.DD):");
        jLabel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel2FocusGained(evt);
            }
        });

        jLabel4.setText("Price per Liter:");

        jLabel5.setText("Total Cost:");

        jLabel6.setText("Fuel Station:");

        daytime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daytimeActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        jButton4.setText("STATISTICS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        car_combobox.setBackground(new java.awt.Color(204, 51, 0));
        car_combobox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, car_combobox, org.jdesktop.beansbinding.ObjectProperty.create(), car_combobox, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);

        car_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car_comboboxActionPerformed(evt);
            }
        });

        jLabel3.setText("Upload invoice picture:");

        jLabel7.setText("Literamount:");

        my_cars.setText("My Car's");
        my_cars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                my_carsActionPerformed(evt);
            }
        });

        jLabel8.setText("Kilometer Status:");

        kmstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kmstatusActionPerformed(evt);
            }
        });

        jButton1.setText("Browse ...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(car_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(31, 31, 31)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(kmstatus)
                                                .addComponent(literamount)
                                                .addComponent(stationname, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(endcost)
                                                .addComponent(ppLiter)
                                                .addComponent(daytime)
                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(my_cars, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(my_cars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(car_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(daytime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ppLiter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(literamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(endcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(stationname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(kmstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jButton1))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delete)
                            .addComponent(save)
                            .addComponent(refresh)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(logout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void daytimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daytimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daytimeActionPerformed

    
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        
        try{
            String sql="DELETE FROM FuelEntry\n" +
            "where (carID="+get_carID("")+" AND stationname=? AND daytime=? AND ppLiter=?\n" +
            "AND literamount=? AND endcost=? AND userID="+get_userID("")+" AND fuelID="+get_fuelID()+" AND kmstatus=?) ";
            
            pst=conn.prepareStatement(sql);
            pst.setString(1, stationname.getText());
            pst.setString(2,daytime.getText());
            pst.setString(3, ppLiter.getText());
            pst.setString(4, literamount.getText());
            pst.setString(5,endcost.getText());
            pst.setString(6, kmstatus.getText());
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Succesfully deleted Fuel Record from history ! Please click on the 'Refresh' Button to update the tableview!  ");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_deleteActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        Update_table("");
    }//GEN-LAST:event_refreshActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        
        
        Login_JFrame newSession = new Login_JFrame();
        JOptionPane.showMessageDialog(null, "Sucessfully logged out from System!");
        close();
        newSession.setVisible(true);
        
    }//GEN-LAST:event_logoutActionPerformed

    private void car_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car_comboboxActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_car_comboboxActionPerformed
    
  public int get_carID(String username){
      username=Login_JFrame.get_username();
      int quan = 0;
      try{
          String sql="SELECT CAR.id\n" +
          "from CAR\n" +
          "JOIN UserData\n" +
          "ON CAR.userID=UserData.id\n" +
          "Where CAR.CarName ='"+(String)car_combobox.getSelectedItem()+
          "' AND UserData.username='"+username+"'";
          pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
          
          while(rs.next()){
              String str = rs.getString("id");
              quan = Integer.parseInt(str);
          }          
          
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
      }
      System.out.println (quan);
      return quan;
  }
  
  public int get_fuelID(){
      int fuelID=0;
      String carname=(String)car_combobox.getSelectedItem();
      
      try{
          String sql= "SELECT FUEL.id\n" +
          "FROM FUEL\n" +
          "JOIN CAR\n" +
          "ON FUEL.id=CAR.fuelID\n" +
          "WHERE CarName like '"+carname+"'";
          
          pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
          
          while(rs.next()){
              String str=rs.getString("id");
              fuelID=Integer.parseInt(str);
          }
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
          
      }
      System.out.println(fuelID);
      return fuelID;
  }
  
  public static int get_userID(String username){
      username = Login_JFrame.get_username();
      int userID=0;
      try{
          String sql="SELECT UserData.id\n" +
                  "From UserData\n" +
                  "where UserData.username='"+username+"'";
          pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
          while(rs.next()){
              String str = rs.getString("id");
              userID = Integer.parseInt(str);
          }
          
          
          
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
      }
      System.out.println(userID);
      return userID;
  }

    
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here
        int carID= get_carID("");
        int userID=get_userID("");
        int fuelID=get_fuelID();
        String s = (String)car_combobox.getSelectedItem();
        
           try{
               String sql= "Insert into FuelEntry(carID,stationname,daytime,ppLiter,literamount,endcost,userID,fuelID,kmstatus) VALUES ("+carID+",?,?,?,?,?,"+userID+","+fuelID+",?)";
               
               
               pst=conn.prepareStatement(sql);
               pst.setString(1, stationname.getText());
               pst.setString(2,daytime.getText());
               pst.setString(3, ppLiter.getText());
               pst.setString(4, literamount.getText());
               pst.setString(5,endcost.getText());
               pst.setString(6, kmstatus.getText());
               pst.execute();
               
               //String sql2="UPDATE FuelEntry SET kmstatus=? Where id="+carID;
               //pst=conn.prepareStatement(sql2);
               //pst.setString(1, kmstatus.getText());
               //pst.execute();
               JOptionPane.showMessageDialog(null, "Fuel Data succesfully recorded! Please click on the 'Refresh' Button to update the tableview!");
               
           }catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
           }
    }//GEN-LAST:event_saveActionPerformed

    private void my_carsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_my_carsActionPerformed
        // TODO add your handling code here:
        close();
        AddNewCar s= new AddNewCar();
        s.setVisible(true);
    }//GEN-LAST:event_my_carsActionPerformed

    private void kmstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kmstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kmstatusActionPerformed

    private void jLabel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2FocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FileChooser s= new FileChooser();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        close();
        Statistics s = new Statistics();
                s.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    public void FillCombobox(String username){
        
        username=Login_JFrame.get_username();
        try{
            String sql="SELECT x.CarName\n" +
            "from CAR x\n" +
            "JOIN UserData y\n" +
            "on x.userID=y.id\n" +
            "where username='"+username+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
                String name= rs.getString("CarName");
                car_combobox.addItem(name);
            }
            
        
        }catch(Exception e){
        
        }
   
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> car_combobox;
    private javax.swing.JTextField daytime;
    private javax.swing.JButton delete;
    private javax.swing.JTextField endcost;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kmstatus;
    private javax.swing.JTextField literamount;
    private javax.swing.JButton logout;
    private javax.swing.JButton my_cars;
    private javax.swing.JTextField ppLiter;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JTextField stationname;
    private javax.swing.JTable table;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
