import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.block.BlockBorder;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;

import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

import javax.swing.SwingUtilities;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.DefaultXYDataset;
import org.jfree.data.xy.XYDataset;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import tanktool3.javaconnect;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Emre
 */


public class Statistics extends javax.swing.JFrame {

    private static int WINDOW_CLOSING;
    


    /**
     * Creates new form Statistics
     */
    public Statistics() {
        initComponents();
        //select all cars in combobox
        selectAllCars();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closingStatistics = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        printCostsForCar = new javax.swing.JLabel();
        printAvgLiters = new javax.swing.JLabel();
        printAvgPrice = new javax.swing.JLabel();
        printMaxRange = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        selectCarInDB = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        chooseStatisticsCombo = new javax.swing.JComboBox<>();
        executeChoosenCar = new javax.swing.JButton();
        excecuteStatistics = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totalRange = new javax.swing.JLabel();
        totalCosts = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("in km");

        closingStatistics.setFont(new java.awt.Font("AppleGothic", 0, 11)); // NOI18N
        closingStatistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left-arrow.png"))); // NOI18N
        closingStatistics.setText("Back");
        closingStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closingStatisticsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jLabel1.setText("Max. Range:");

        jLabel2.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jLabel2.setText("Max. Costs:");

        jLabel3.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jLabel3.setText("Avg. (l/100km):");

        jLabel4.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jLabel4.setText("Avg. Price(kind Fuel):");

        printCostsForCar.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        printCostsForCar.setText("in EUR");

        printAvgLiters.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        printAvgLiters.setText("in liters");

        printAvgPrice.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        printAvgPrice.setText("in EUR");

        printMaxRange.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        printMaxRange.setText("in KM");

        jLabel10.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jLabel10.setText("Choose a Car:");

        selectCarInDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCarInDBActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jLabel11.setText("Statistics:");

        chooseStatisticsCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Last Entrys", "Fuel Price (in liters)", "Total Odemeter", "Liters for 100 KM" }));
        chooseStatisticsCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseStatisticsComboActionPerformed(evt);
            }
        });

        executeChoosenCar.setFont(new java.awt.Font("AppleGothic", 0, 11)); // NOI18N
        executeChoosenCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cogwheel-setting.png"))); // NOI18N
        executeChoosenCar.setText("Execute");
        executeChoosenCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeChoosenCarActionPerformed(evt);
            }
        });

        excecuteStatistics.setFont(new java.awt.Font("AppleGothic", 0, 11)); // NOI18N
        excecuteStatistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cogwheel-setting.png"))); // NOI18N
        excecuteStatistics.setText("Execute");
        excecuteStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excecuteStatisticsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jLabel5.setText("Total Costs:");

        jLabel6.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        jLabel6.setText("Total Range:");

        totalRange.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalRange.setText("in KM");

        totalCosts.setFont(new java.awt.Font("AppleGothic", 0, 14)); // NOI18N
        totalCosts.setText("in EUR");

        jLabel7.setFont(new java.awt.Font("AppleGothic", 3, 16)); // NOI18N
        jLabel7.setText("Choosen car:");

        jLabel8.setFont(new java.awt.Font("AppleGothic", 3, 16)); // NOI18N
        jLabel8.setText("All cars:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(executeChoosenCar)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(selectCarInDB, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(printMaxRange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(printCostsForCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(printAvgLiters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(printAvgPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(13, 13, 13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chooseStatisticsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(excecuteStatistics, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(closingStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalRange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalCosts, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)))
                            .addComponent(jLabel8))
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectCarInDB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(executeChoosenCar)
                            .addComponent(excecuteStatistics))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(printMaxRange))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(printCostsForCar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(printAvgLiters))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(printAvgPrice))
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseStatisticsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(totalRange))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(totalCosts))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(closingStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //if klick the back button than close the statistic frame and open the mainwindow frame
    private void closingStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closingStatisticsActionPerformed
        close();
        MainWindow s = new MainWindow();
        s.setVisible(true);
        
       
    }//GEN-LAST:event_closingStatisticsActionPerformed
   
    //method to clse frames
    public void close(){
        WindowEvent winClosingEvent =  new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
   
    
    //mothod for choosing a chart
    private void chooseStatisticsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseStatisticsComboActionPerformed
        String[] statistics ={"Monthly Costs", "Fuel Price (in liters)", "Total Odemeter" , "Fill up Costs"};
      //  return statistics;
        /*
        Monthly Costs: x=Date, y = costs
        Fuel Price in liters: x = Date, y = Euro
        Total Odemeter: x = Date, y = KM
        Fill up Costs: x = Date, y = KM
        */
        
    }//GEN-LAST:event_chooseStatisticsComboActionPerformed

    
    private void selectCarInDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCarInDBActionPerformed
            //ToDO
    }//GEN-LAST:event_selectCarInDBActionPerformed

    
    //fill all labels with the data
    private void executeChoosenCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeChoosenCarActionPerformed
        //take the car id with the carname
        String query = "select id from CAR where CarName = ?;";
             Connection conn = new javaconnect().ConnecrDb();
           PreparedStatement pst=null;
           ResultSet rs = null;
        
           //value = carname
           String value = selectCarInDB.getSelectedItem().toString();
            try { 
                pst = conn.prepareStatement(query);  
                pst.setString(1, value);
                rs = pst.executeQuery();
           
                //take username
           String username = Login_JFrame.getUsername();
           //getid 
            int id = MainWindow.get_userID(username);
            
        

//Labels werden ausgefüllt
        searchMaxRange(id);
        calculateMaxCosts(id);
        calculateAvgLiters(id);
        calculateAvgPrice(id);
        calculateCarCosts(id);
        caluclateMaxRange(id);
        
            } catch (SQLException ex) {
                Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    //closing connection
                    if(conn != null)conn.close();
                    if(rs != null)rs.close();
                    if(pst!= null)pst.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                }
       
        
            }   
    }//GEN-LAST:event_executeChoosenCarActionPerformed

    private void excecuteStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excecuteStatisticsActionPerformed
               //check witch chart is choosen
        String value = chooseStatisticsCombo.getSelectedItem().toString();
        
        
        //open chart in a new window
        if(value.equals("Last Entrys")){
                JFrame frame = new JFrame("Chart: Last Entrys");
                frame.setSize(600, 400);
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.setVisible(true);
                XYDataset ds = xycreateDataset();
                JFreeChart chart = ChartFactory.createXYLineChart("FILL-UP-Costs Chart",
                        "entrys", "costs", ds, PlotOrientation.VERTICAL, true, true,
                        false);

                ChartPanel cp = new ChartPanel(chart);
                frame.getContentPane().add(cp);
                
        }else if(value.equals("Liters for 100 KM")){
          JFrame frame = new JFrame("Chart: Consuption for 100 KM");
/*
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setVisible(true);
*/
                CategoryDataset dataset = carsAtOneHundredKilometerCreateDataset();
                JFreeChart chart =  CarsAtOnHundredCreateChart(dataset);
                ChartPanel chartPanel = new ChartPanel(chart);
                chartPanel.setFillZoomRectangle(true);
                chartPanel.setMouseWheelEnabled(true);
                chartPanel.setPreferredSize(new Dimension(500, 270));
                frame.setContentPane(chartPanel);frame.setSize(600, 400);
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.setVisible(true);
            
            
        }else if(value.equals("Total Odemeter")){
            
              JFrame frame = new JFrame("Chart: Total Odemeter");
/*
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setVisible(true);         
*/              CategoryDataset dataset = createDataset();
                JFreeChart chart =  createChart(dataset);
                ChartPanel chartPanel = new ChartPanel(chart);
                chartPanel.setFillZoomRectangle(true);
                chartPanel.setMouseWheelEnabled(true);
                chartPanel.setPreferredSize(new Dimension(500, 270));
                frame.setContentPane(chartPanel);frame.setSize(600, 400);
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.setVisible(true);
                
        }else if(value.equals("Fuel Price (in liters)")){
            JFrame frame = new JFrame("Chart: Fuel Price");
/*
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setVisible(true);            
*/
                CategoryDataset dataset = fuelPricecreateDataset();
                JFreeChart chart =  FuelLiterCreateChart(dataset);
                ChartPanel chartPanel = new ChartPanel(chart);
                chartPanel.setFillZoomRectangle(true);
                chartPanel.setMouseWheelEnabled(true);
                chartPanel.setPreferredSize(new Dimension(500, 270));
                frame.setContentPane(chartPanel);frame.setSize(600, 400);
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.setVisible(true);
            
        
        }
  
    }//GEN-LAST:event_excecuteStatisticsActionPerformed

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> chooseStatisticsCombo;
    private javax.swing.JButton closingStatistics;
    private javax.swing.JButton excecuteStatistics;
    private javax.swing.JButton executeChoosenCar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel printAvgLiters;
    private javax.swing.JLabel printAvgPrice;
    private javax.swing.JLabel printCostsForCar;
    private javax.swing.JLabel printMaxRange;
    private javax.swing.JComboBox<String> selectCarInDB;
    private javax.swing.JLabel totalCosts;
    private javax.swing.JLabel totalRange;
    // End of variables declaration//GEN-END:variables

    
    //set in label the max range of the choosen car
    private void searchMaxRange(int id) {
        String query = "select c.kmstatus ,max(f.kmstatus) from fuelentry f, car c\n" +
        "where f.carID = c.id and c.userID = ? and CarName = ?;";
        Connection conn = new javaconnect().ConnecrDb();
           PreparedStatement pst=null;
           ResultSet rs = null;
        
        try {
            pst = conn.prepareStatement(query);
            //get userid
            pst.setInt(1, MainWindow.get_userID(Login_JFrame.getUsername()));
            //take carname from combobox
            pst.setString(2, selectCarInDB.getSelectedItem().toString());
            rs = pst.executeQuery();
            
            int kmstatusCar=0;
            int kmstatusFuel=0;
            
            //take the values
            while(rs.next()){
                kmstatusCar = Integer.parseInt(rs.getString(1));
                kmstatusFuel = rs.getInt(2);
            }
            //subtract the difference
            kmstatusFuel-=kmstatusCar;
            //print it on label
            printMaxRange.setText(kmstatusFuel+" KM");
            
        } catch (SQLException ex) {
            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
                try {
                    if(conn != null)conn.close();
                    if(rs != null)rs.close();
                    if(pst!= null)pst.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                }
       
        
            }   
        
        
        
    }

    //calculate the fuel costs of the car
    private void calculateCarCosts(int id){
        Connection conn = new javaconnect().ConnecrDb();
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        //get car id
       String query = "select id from car where carname = ?";
        try {
            
            pst = conn.prepareStatement(query);
            pst.setString(1, selectCarInDB.getSelectedItem().toString());
            rs = pst.executeQuery();
            int carid=0; 
            
            while(rs.next()){
                carid = rs.getInt(1);
            }

            //get the endcost form the carid and the userid
            query = "select endcost from fuelentry WHERE  userid = ? and carID = ?;";
            pst = conn.prepareStatement(query);
            pst.setInt(1, id);
            pst.setInt(2, carid);
            rs = pst.executeQuery();
            
            double erg= 0;
            double value = 0;
            
            //take result and add up
            while(rs.next()){
                value = rs.getDouble(1);
                erg +=value;
            }
            
            //round it to two diciaml palces
            erg*=100;
            erg = Math.round(erg);
            erg /= 100;
            
            //print it on label
            printCostsForCar.setText(Double.toString(erg)+" EUR");
        } catch (SQLException ex) {
            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    //caluclat the driving range of all your cars
    private void caluclateMaxRange(int id){
         Connection conn = new javaconnect().ConnecrDb();
           PreparedStatement pst=null;
           ResultSet rs = null;
          
         try {
             //get the information from the car fleet
            String query = "select c.kmstatus, c.CarName, max(f.kmstatus) , f.daytime from fuelentry f, car c\n" +
                    "where f.carID = c.id and c.userID = ?\n" +
                    "GROUP BY c.CarName;";
           
            pst = conn.prepareStatement(query);
            //set userid
            pst.setInt(1, id);
            rs = pst.executeQuery();
            
            int value = 0;
            while(rs.next()){
                int kmFirst = rs.getInt(1);
                int kmstatus = rs.getInt(3);
                String carName = rs.getString(2);
                //difference of max kmstatus from fuelentry and kmstatus if you add a new car
                kmstatus -= kmFirst;
                value +=kmstatus;
            }
            String text = Integer.toString(value);
            //print it in the label
            totalRange.setText(text+" KM");
        } catch (SQLException ex) {
            ex.printStackTrace();
        } finally{
                try {
                    if(conn != null)conn.close();
                    if(rs != null)rs.close();
                    if(pst!= null)pst.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                }
       
        
            }   
        
    }
    
    
    //fuel Costs of all your entry in the db of your own cars
    private void calculateMaxCosts(int id) {
         Connection conn = new javaconnect().ConnecrDb();
           PreparedStatement pst=null;
           ResultSet rs = null;
          String query = "select endcost from fuelentry where userid = ?;";
         try {
            pst = conn.prepareStatement(query);
            pst.setInt(1, id);
            rs = pst.executeQuery();
            
            double value = 0;
            double erg=0;
            while(rs.next()){
                value = rs.getInt(1);
                //caluculate the value
                erg += value;
            }
            
            query = Double.toString(erg);
            //print the fuel cost of all your cars in the label
            totalCosts.setText(query +" €");
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        } finally{
                try {
                    if(conn != null)conn.close();
                    if(rs != null)rs.close();
                    if(pst!= null)pst.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                }
       
        
            }   
        
    }

    //avg price of the fuel of the car
    private void calculateAvgPrice(int id) {
            String query = "select fuelentry.ppliter from fuelentry , fuel where fuelentry.fuelid = fuel.id and fuelentry.userid = ?;";
            
            Connection conn = new javaconnect().ConnecrDb();
           PreparedStatement pst=null;
           ResultSet rs = null;
            
            try {
                pst = conn.prepareStatement(query);
                pst.setInt(1, id);
                rs = pst.executeQuery();
                
                double value=0;
                double valueCost=0;
                
                while(rs.next()){
                    value = rs.getInt(1);
                    valueCost += value;
                }
                System.out.println("PPLiter: "+valueCost);
                
                query = "select count(*) from FuelEntry, fuel where fuelentry.fuelid = fuel.id;";
                pst = conn.prepareStatement(query);
                rs = pst.executeQuery();
                while(rs.next()){
                     int anzahl = rs.getInt(1); 
                     valueCost /= anzahl;
                }
            
               //round up
               valueCost*=100;
               valueCost = Math.round(valueCost);
               valueCost /=100;
                
               //take it on label
                printAvgPrice.setText(Double.toString(valueCost)+" Euro");
                
                
                
        } catch (SQLException ex) {
            ex.printStackTrace();
        }finally{
                try {
                    if(conn != null)conn.close();
                    if(rs != null)rs.close();
                    if(pst!= null)pst.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                }
       
        
            }   
    }

    //calculate user consuption of the car
    private void calculateAvgLiters(int id) {
       //(Number of litres X 100) / (km at the end – km at the beginning)
       
       //liters
            Connection conn = new javaconnect().ConnecrDb();
            pst=null;
           rs = null;
           //take only the id where userid and carname the same because carname is not unique 
           //that means if you dont do it than get values from another user
       String query = "select id from car where carname = ? and userid = ?";
        try {
            
            pst = conn.prepareStatement(query);
            pst.setString(1, selectCarInDB.getSelectedItem().toString());
            pst.setInt(2, id);
            rs = pst.executeQuery();
            int carid=0; 
            
            while(rs.next()){
                carid = rs.getInt(1);
            }

            
            query = "select literamount, carID from FuelEntry f, fuel g where f.fuelID=g.id and userid = ? and carID = ?;";
            pst = conn.prepareStatement(query);
            pst.setInt(1, id);
            pst.setInt(2, carid);
            rs = pst.executeQuery();
            
            double value = 0;
            double erg = 0;
            
            while(rs.next()){
                value = rs.getDouble(1);
                erg += value;
            }
       
            
            query = "select max(f.kmstatus), c.kmstatus from fuelentry f, car c where f.userid = ? and f.carID = ? and f.carID = c.id;";
           pst = conn.prepareStatement(query);
           pst.setInt(1, id);
           pst.setInt(2, carid);
           rs = pst.executeQuery();
           
           int maxKM =0;
           int kmMin=0;
           while(rs.next()){
               maxKM = rs.getInt(1);
               kmMin = Integer.parseInt(rs.getString(2));
           }
           int km = maxKM-kmMin;
           
           double ergebnis = erg * 100 / km;
            
           ergebnis *= 1000;
           ergebnis = Math.round(ergebnis);
           ergebnis/=1000;
          
           printAvgLiters.setText(Double.toString(ergebnis)+" l"); 
            
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }finally{
                try {
                    if(conn != null)conn.close();
                    if(rs != null)rs.close();
                    if(pst!= null)pst.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                }
       
        
            }   
      
    }
    
    
    
    //charts
    
    //chart fill up costs
      private static XYDataset xycreateDataset() {
        /*
            fill up costs :x-date, y-km
        */
        //creating dataset (values) for chart
        DefaultXYDataset ds = new DefaultXYDataset();

        Connection conn =  new javaconnect().ConnecrDb();

        //getUsername
        String username = Login_JFrame.getUsername();
        //getid
        int id = MainWindow.get_userID(username);
        //count the fuel entrys
        String query = "SELECT Count(*) from fuelentry where userid = ?";
        try {
            pst = conn.prepareStatement(query);
            pst.setInt(1, id);
             rs = pst.executeQuery();
             int count=0;
             while(rs.next()){
                 count = rs.getInt(1);
             }

            System.out.println(count);

            //search in db every entry fuelentry with the id, only the last 30 once with desc
            query = "select endcost from fuelentry where userid = ? ORDER  by id DESC ";

            pst = conn.prepareStatement(query);
            pst.setInt(1, id);
            rs  = pst.executeQuery();



            int counter=0;
            double i=1.0;
            double[] entrys = new double[count];
            double[] costs = new double[count];

            while(rs.next() && counter < 30){   //take values and the loop only getting 30 times
                costs[counter] = rs.getDouble(1);   //set it array  , costs = y axis
                entrys[counter] = i;                //entry = x axis
                i++;                            //increase counter and i
                counter++;

            }
            
            //set into data
            double[][] data = { entrys, costs };
            //take it to the xy chart
            ds.addSeries("Fill-Up-Costs", data);

            return ds;

        } catch (SQLException e) {
            e.printStackTrace();
        } finally{
                try {
                    if(conn != null)conn.close();
                    if(rs != null)rs.close();
                    if(pst!= null)pst.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                }
       
        
            }   
        return ds = null;
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    //chart Total Odemeter 
    private static JFreeChart createChart(CategoryDataset dataset) {
        //set the information titel, x-axis and y-axis with the values
        JFreeChart chart = ChartFactory.createBarChart("Total Odemeter", "Cars" ,"Kilometer" , dataset);
        
        //crating the chart
        CategoryPlot plot = (CategoryPlot) chart.getPlot();
        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setDrawBarOutline(false);
        chart.getLegend().setFrame(BlockBorder.NONE);
        return chart;
    }

    static ResultSet rs = null;
    static PreparedStatement pst = null;
    
    private static CategoryDataset createDataset() {
           Connection conn = new javaconnect().ConnecrDb();
           DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        try {
            String username = Login_JFrame.get_username();
            int id = MainWindow.get_userID(username);
            //get information about max kmstatus from table fuelentry and kmstatus from table car group be carname
            String query = "select c.kmstatus, c.CarName, max(f.kmstatus) , f.daytime from fuelentry f, car c\n" +
                    "where f.carID = c.id and c.userID = ?\n" +
                    "GROUP BY c.CarName;";
           
            pst = conn.prepareStatement(query);
            pst.setInt(1, id);
            rs = pst.executeQuery();
            
            //take the difference and put it on dataset
            while(rs.next()){
                int kmFirst = rs.getInt(1);
                int kmstatus = rs.getInt(3);
                String carName = rs.getString(2);
                kmstatus -= kmFirst;
                dataset.addValue(kmstatus, carName, carName);
            }
           //return dataset
            return  dataset;
        } catch (SQLException e) {
            e.printStackTrace();
        }finally{
                try {
                    if(conn != null)conn.close();
                    if(rs != null)rs.close();
                    if(pst!= null)pst.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                }
       
        
            }   
        return  null;


    }

    
    
    
    
    
    
    /*
    Liters price Fuel
    */
    private static JFreeChart FuelLiterCreateChart(CategoryDataset dataset) {
        //set all information titel x-axis and y-axis
        JFreeChart chart = ChartFactory.createBarChart("Fuel-Cost-Chart", "Fuel" ,"Price" , dataset);
        //creating chart
        CategoryPlot plot = (CategoryPlot) chart.getPlot();
        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setDrawBarOutline(false);
        chart.getLegend().setFrame(BlockBorder.NONE);
        return chart;
    }
    private CategoryDataset fuelPricecreateDataset() {
         DefaultCategoryDataset dataset = new DefaultCategoryDataset();
         Connection conn = new javaconnect().ConnecrDb();

        try {

            //getUsername
            String username = Login_JFrame.getUsername();
            //getid
            int id = MainWindow.get_userID(username);
            
            //avg price for the fuel
            String query = "select avg(ppLiter), fuelName from fuelentry f, fuel s where s.id=f.fuelID and userid = ? GROUP BY fuelID;";
            pst = conn.prepareStatement(query);
            pst.setInt(1, id);
            rs = pst.executeQuery();

            while(rs.next()){
                double avg = rs.getDouble(1);
                String fuelName = rs.getString(2);
                dataset.addValue(avg, fuelName, fuelName);
            }

            return  dataset;
        } catch (SQLException e) {
            e.printStackTrace();
        }finally{
                try {
                    if(conn != null)conn.close();
                    if(rs != null)rs.close();
                    if(pst!= null)pst.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                }
       
        
            }   
        return  null;


    }

    
    
    
    private CategoryDataset carsAtOneHundredKilometerCreateDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        Connection conn = new javaconnect().ConnecrDb();
        
        String username = Login_JFrame.getUsername();
        int id = MainWindow.get_userID(username);
          
        String query = "select count(*) from car where userid = ?";
                
        try {
            pst = conn.prepareStatement(query);
            pst.setInt(1, id);
            rs = pst.executeQuery();
            int count=0;
                   while(rs.next()){ 
                    count = rs.getInt(1);
                   }
            System.out.println("zählung von autos: "+count);
            
            
            query = "select carname from car where userid = ?";
            pst = conn.prepareStatement(query);
            pst.setInt(1, id);
            rs = pst.executeQuery();
            String[] carName = new String[count];
            int i=0;
            while(rs.next()){
                carName[i] = rs.getString(1);
                System.out.println(carName[i]);
                i++;
            }
            
            
            for(int j=0; j<count; j++){
                double value = calculateLitersPerOneHundredKM(carName[j], id);        //calculte consumption for each car
                dataset.addValue(value, carName[j], carName[j]);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
        return dataset;

    }
    
    private double calculateLitersPerOneHundredKM(String car, int id){
       //liters
            Connection conn = new javaconnect().ConnecrDb();
            pst=null;
            rs = null;
            //search carid
       String query = "select id from car where carname = ? and userid = ?";
        try {
            
            pst = conn.prepareStatement(query);
            pst.setString(1, car);
            pst.setInt(2, id);
            rs = pst.executeQuery();
            int carid=0; 
            
            while(rs.next()){
                carid = rs.getInt(1);
            }

            //get literamount and carid
            query = "select literamount, carID from FuelEntry f, fuel g where f.fuelID=g.id and userid = ? and carID = ?;";
            pst = conn.prepareStatement(query);
            pst.setInt(1, id);
            pst.setInt(2, carid);
            rs = pst.executeQuery();
            
            double value = 0;
            double erg = 0;
            
            while(rs.next()){
                value = rs.getDouble(1);
                erg += value;               //sum up literamount
            }
       
            
            //get max kmstatus
            query = "select max(f.kmstatus), c.kmstatus from fuelentry f, car c where f.userid = ? and f.carID = ? and f.carID = c.id;";
           pst = conn.prepareStatement(query);
           pst.setInt(1, id);
           pst.setInt(2, carid);
           rs = pst.executeQuery();
           
           int maxKM =0;
           int kmMin=0;
           while(rs.next()){
               maxKM = rs.getInt(1);
               kmMin = Integer.parseInt(rs.getString(2));
           }
           int km = maxKM-kmMin;            //make difference
           
           double ergebnis = erg * 100 / km;
            
           ergebnis *= 1000;
           ergebnis = Math.round(ergebnis);
           return ergebnis/=1000;
           
        } catch (SQLException ex) {
            ex.printStackTrace();
        }finally{
                try {
                    if(conn != null)conn.close();
                    if(rs != null)rs.close();
                    if(pst!= null)pst.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                }       
        }  
        return 0; 
}    

    private JFreeChart CarsAtOnHundredCreateChart(CategoryDataset dataset) {
        JFreeChart chart = ChartFactory.createBarChart("Consuption Per Onhundred Kilometer", "Cars" ,"Liters" , dataset);
        CategoryPlot plot = (CategoryPlot) chart.getPlot();
        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setDrawBarOutline(false);
        chart.getLegend().setFrame(BlockBorder.NONE);
        return chart;
    }

    
    
    
    
    
    
    
    //all cars in combobox
    private String selectAllCars() {
     Connection conn = new javaconnect().ConnecrDb();
     
        String username=Login_JFrame.getUsername();
        try{
            String sql="SELECT x.CarName\n" +
            "from CAR x\n" +
            "JOIN UserData y\n" +
            "on x.userID=y.id\n" +
            "where username='"+username+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
                String name= rs.getString("CarName");
                selectCarInDB.addItem(name);
            }
          
        } catch (SQLException ex) {
            Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
                try {
                    if(conn != null)conn.close();
                    if(rs != null)rs.close();
                    if(pst!= null)pst.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Statistics.class.getName()).log(Level.SEVERE, null, ex);
                }
            
        }
           return null; 
    }
}
